(source melpa)
(source org)
(source marmalade)
(source gnu)
(source "tromey" "http://tromey.com/elpa/")

(depends-on "pallet")
(depends-on "erlang-emacs" :git "git@github.com:lehoff/erlang-emacs.git")
(depends-on "magit")
(depends-on "idle-highlight-mode")
(depends-on "alchemist" :git "git://github.com/tonini/alchemist.el.git")
(depends-on "flymake-elixir" :git "git@github.com:syl20bnr/flymake-elixir.git")
(depends-on "ruby-end" :git "git@github.com:rejeep/ruby-end.git")
(depends-on "tuareg")
(depends-on "caml")
(depends-on "org-plus-contrib")
(depends-on "auctex")
;;(depends-on "preview-latex")
(depends-on "adoc-mode")
(depends-on "fuzzy")
(depends-on "auto-complete")
(depends-on "csv-mode")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "elixir" :git "https://github.com/elixir-lang/emacs-elixir")
(depends-on "graphviz-dot-mode")
(depends-on "json")
;;(depends-on "js2")
(depends-on "markdown-mode")
;;(depends-on "ssh-config")
